package tw.core;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import tw.core.generator.AnswerGenerator;
import tw.core.model.GuessResult;

import java.util.ArrayList;
import java.util.List;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.Is.is;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

public class GameTest {

    private final Answer actualAnswer = Answer.createAnswer("1 2 3 4");
    private Game game;

    @BeforeEach
    public void setUp() throws Exception {
        AnswerGenerator answerGenerator = mock(AnswerGenerator.class);
        when(answerGenerator.generate()).thenReturn(actualAnswer);
        game = new Game(answerGenerator);
    }


    @Test
    public void should_get_the_success_status_when_guess_input_is_correct() throws Exception {

        //given
//        excuteSuccessGuess();
        GuessResult guess = game.guess(Answer.createAnswer("1 2 3 4"));
        //when
        //then
        assertThat(guess.getResult(), is("4A0B"));

    }

    @Test
    public void should_get_the_failed_status_when_guess_input_is_incorrect() throws Exception {

        //given
//        excuteFailedGuess();
        GuessResult guess = game.guess(Answer.createAnswer("1 2 3 3"));
        //when
        //then
        assertThat(guess.getResult(), is("3A0B"));

    }

    @Test
    public void should_get_the_success_guess_history_when_call_guessHistory() throws Exception{
        //given
        List<GuessResult> guessResults = new ArrayList<>();
        GuessResult guess = game.guess(Answer.createAnswer("1 2 3 3"));
        guessResults.add(guess);
        //then
        assertThat(game.guessHistory(),is(guessResults));
    }

}
